### ISSUE TITLE
hash in URL

### ISSUE THREAD

**Issue by michalhisim** [casualrelaxation/gulp-css-url-adjuster#18]
Some icon font formats needs hash in URL. With append it look like this example:

```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("/fonts/glyphicons-halflings-regular.eot?v5");
  src: url("/fonts/glyphicons-halflings-regular.eot?#iefix?v5")format('embedded-opentype'),
         url("/fonts/glyphicons-halflings-regular.woff?v5")format('woff'),
         url("/fonts/glyphicons-halflings-regular.ttf?v5")format('truetype'),
         url("/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular?v5")format('svg');
}
```

Sadly there is no way to do it correct like this:

```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("/fonts/glyphicons-halflings-regular.eot?v5");
  src: url("/fonts/glyphicons-halflings-regular.eot?v5#iefix")format('embedded-opentype'),
         url("/fonts/glyphicons-halflings-regular.woff?v5")format('woff'),
         url("/fonts/glyphicons-halflings-regular.ttf?v5")format('truetype'),
         url("/fonts/glyphicons-halflings-regular.svg?v5#glyphicons_halflingsregular")format('svg');
}
```

It will be cool to have an option to solve this problem correctly.
